### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by hackpwnpwn** [0x09AL/IIS-Raid#7]
I also encountered the same problem, I got a 503 error after following the steps to install the module

My environment is x64, and I also compiled x64 dll

**Comment by alzaaba6** [comment]
Same here

**Comment by BAbrandon** [comment]
I am having the same issues I think it has something to do with the version of visual studio

**Comment by thr0wCat** [comment]
> I am having the same issues I think it has something to do with the version of visual studio

same here is there a solver

**Comment by 0x09AL** [comment]
Make sure to correctly compile the module and not use the Debug release.

**Comment by kimboslice99** [comment]
I've had issues compiling modules for IIS using VS 2022 and now use 2019 only to avoid headaches

Just something to check. No problems here, great work @0x09AL
